<a href="https://colab.research.google.com/github/amriteshamr/AI-Threat-Detection/blob/main/main_nn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("Friday-WorkingHours-Morning.pcap_ISCX.csv")
df2 = pd.read_csv("Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv")
df3 = pd.read_csv("Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv")
df4 = pd.read_csv("Monday-WorkingHours.pcap_ISCX.csv")
df5 = pd.read_csv("Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv")
df6 = pd.read_csv("Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv")
df7 = pd.read_csv("Tuesday-WorkingHours.pcap_ISCX.csv")
df8 = pd.read_csv("Wednesday-workingHours.pcap_ISCX.csv")

In [3]:
df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8])

In [4]:
df.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,3268,112740690,32,16,6448,1152,403,0,201.5,204.724205,...,32,3.594286e+02,1.199802e+01,380,343,16100000.0,4.988048e+05,16400000,15400000,BENIGN
1,389,112740560,32,16,6448,5056,403,0,201.5,204.724205,...,32,3.202857e+02,1.574499e+01,330,285,16100000.0,4.987937e+05,16400000,15400000,BENIGN
2,0,113757377,545,0,0,0,0,0,0.0,0.000000,...,0,9.361829e+06,7.324646e+06,18900000,19,12200000.0,6.935824e+06,20800000,5504997,BENIGN
3,5355,100126,22,0,616,0,28,28,28.0,0.000000,...,32,0.000000e+00,0.000000e+00,0,0,0.0,0.000000e+00,0,0,BENIGN
4,0,54760,4,0,0,0,0,0,0.0,0.000000,...,0,0.000000e+00,0.000000e+00,0,0,0.0,0.000000e+00,0,0,BENIGN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2830743 entries, 0 to 692702
Data columns (total 79 columns):
 #   Column                        Dtype
---  ------                        -----
 0    Destination Port             int64
 1    Flow Duration                int64
 2    Total Fwd Packets            int64
 3    Total Backward Packets       int64
 4   Total Length of Fwd Packets   int64
 5    Total Length of Bwd Packets  int64
 6    Fwd Packet Length Max        int64
 7    Fwd Packet Length Min        int64
 8    Fwd Packet Length Mean       float64
 9    Fwd Packet Length Std        float64
 10  Bwd Packet Length Max         int64
 11   Bwd Packet Length Min        int64
 12   Bwd Packet Length Mean       float64
 13   Bwd Packet Length Std        float64
 14  Flow Bytes/s                  float64
 15   Flow Packets/s               float64
 16   Flow IAT Mean                float64
 17   Flow IAT Std                 float64
 18   Flow IAT Max                 int64
 19   Flow IAT Min                 int64
 20  Fwd IAT Total                 int64
 21   Fwd IAT Mean                 float64
 22   Fwd IAT Std                  float64
 23   Fwd IAT Max                  int64
 24   Fwd IAT Min                  int64
 25  Bwd IAT Total                 int64
 26   Bwd IAT Mean                 float64
 27   Bwd IAT Std                  float64
 28   Bwd IAT Max                  int64
 29   Bwd IAT Min                  int64
 30  Fwd PSH Flags                 int64
 31   Bwd PSH Flags                int64
 32   Fwd URG Flags                int64
 33   Bwd URG Flags                int64
 34   Fwd Header Length            int64
 35   Bwd Header Length            int64
 36  Fwd Packets/s                 float64
 37   Bwd Packets/s                float64
 38   Min Packet Length            int64
 39   Max Packet Length            int64
 40   Packet Length Mean           float64
 41   Packet Length Std            float64
 42   Packet Length Variance       float64
 43  FIN Flag Count                int64
 44   SYN Flag Count               int64
 45   RST Flag Count               int64
 46   PSH Flag Count               int64
 47   ACK Flag Count               int64
 48   URG Flag Count               int64
 49   CWE Flag Count               int64
 50   ECE Flag Count               int64
 51   Down/Up Ratio                int64
 52   Average Packet Size          float64
 53   Avg Fwd Segment Size         float64
 54   Avg Bwd Segment Size         float64
 55   Fwd Header Length.1          int64
 56  Fwd Avg Bytes/Bulk            int64
 57   Fwd Avg Packets/Bulk         int64
 58   Fwd Avg Bulk Rate            int64
 59   Bwd Avg Bytes/Bulk           int64
 60   Bwd Avg Packets/Bulk         int64
 61  Bwd Avg Bulk Rate             int64
 62  Subflow Fwd Packets           int64
 63   Subflow Fwd Bytes            int64
 64   Subflow Bwd Packets          int64
 65   Subflow Bwd Bytes            int64
 66  Init_Win_bytes_forward        int64
 67   Init_Win_bytes_backward      int64
 68   act_data_pkt_fwd             int64
 69   min_seg_size_forward         int64
 70  Active Mean                   float64
 71   Active Std                   float64
 72   Active Max                   int64
 73   Active Min                   int64
 74  Idle Mean                     float64
 75   Idle Std                     float64
 76   Idle Max                     int64
 77   Idle Min                     int64
 78   Label                        object
dtypes: float64(24), int64(54), object(1)
memory usage: 1.7+ GB

In [6]:
df.isnull().sum()

 Destination Port              0
 Flow Duration                 0
 Total Fwd Packets             0
 Total Backward Packets        0
Total Length of Fwd Packets    0
                              ..
Idle Mean                      0
 Idle Std                      0
 Idle Max                      0
 Idle Min                      0
 Label                         0
Length: 79, dtype: int64

In [7]:
df.columns = df.columns.str.strip()

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [9]:
y = le.fit_transform(df['Label'])

In [10]:
X = df.drop('Label', axis=1)

In [11]:
import numpy as np
X.replace([np.inf, -np.inf], np.nan, inplace=True)
X.fillna(0, inplace=True)

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [23]:
model = Sequential()
model.add(Dense(64, input_dim=X_train.shape[1], activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(15, activation='softmax'))

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [26]:
from tensorflow.keras.optimizers import Adam
opt = Adam(learning_rate=0.0001)

In [27]:
model.compile(loss='sparse_categorical_crossentropy', optimizer=opt, metrics=['accuracy'])

In [16]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [18]:
pd.DataFrame(X_train).describe()

,0,1,2,3,4,5,6,7,8,9,...,68,69,70,71,72,73,74,75,76,77
count,2.264594e+06,2.264594e+06,2.264594e+06,2.264594e+06,2.264594e+06,2.264594e+06,2.264594e+06,2.264594e+06,2.264594e+06,2.264594e+06,...,2.264594e+06,2.264594e+06,2.264594e+06,2.264594e+06,2.264594e+06,2.264594e+06,2.264594e+06,2.264594e+06,2.264594e+06,2.264594e+06
mean,-2.045098e-17,-2.001799e-18,1.819818e-19,6.714499e-19,1.344469e-18,-3.749452e-19,-1.156055e-17,-3.211507e-17,1.551551e-18,-1.017545e-16,...,9.883492e-20,3.051332e-19,-1.185235e-17,-3.478675e-17,-4.878994e-18,1.013136e-17,-1.755183e-17,-2.460440e-17,5.873618e-18,3.147029e-17
std,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,...,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
min,-4.412352e-01,-4.393617e-01,-1.104874e-02,-1.034559e-02,-8.263861e-02,-7.243537e-03,-2.896145e-01,-3.102603e-01,-3.129316e-01,-2.451818e-01,...,-8.472509e-03,-4.641276e+02,-1.255970e-01,-1.056783e-01,-1.495909e-01,-1.005629e-01,-3.518244e-01,-1.092664e-01,-3.567468e-01,-3.389292e-01
25%,-4.383355e-01,-4.393568e-01,-9.780875e-03,-9.392579e-03,-8.082406e-02,-7.243115e-03,-2.812472e-01,-3.102603e-01,-2.806660e-01,-2.451818e-01,...,-8.472509e-03,2.716712e-03,-1.255970e-01,-1.056783e-01,-1.495909e-01,-1.005629e-01,-3.518244e-01,-1.092664e-01,-3.567468e-01,-3.389292e-01
50%,-4.368584e-01,-4.384310e-01,-9.780875e-03,-8.439572e-03,-7.326344e-02,-7.191700e-03,-2.380162e-01,-2.770933e-01,-1.300931e-01,-2.451818e-01,...,-6.971547e-03,2.720170e-03,-1.255970e-01,-1.056783e-01,-1.495909e-01,-1.005629e-01,-3.518244e-01,-1.092664e-01,-3.567468e-01,-3.389292e-01
75%,-4.169985e-01,-3.441082e-01,-5.977282e-03,-6.533560e-03,-5.436189e-02,-7.040405e-03,-1.766561e-01,2.867469e-01,-4.405144e-02,-1.521326e-01,...,-5.470584e-03,2.727086e-03,-1.255970e-01,-1.056783e-01,-1.495909e-01,-1.005629e-01,-3.518244e-01,-1.092664e-01,-3.567468e-01,-3.389292e-01
max,3.144212e+00,3.125169e+00,2.786123e+02,2.781931e+02,4.333088e+02,2.762237e+02,3.432309e+01,3.824645e+01,3.163464e+01,2.482642e+01,...,3.205325e+02,2.818724e-03,1.695435e+02,1.804764e+02,1.074919e+02,1.896461e+02,4.727490e+00,1.662578e+01,4.569409e+00,4.798205e+00

In [22]:
print(np.unique(y))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

In [28]:
model.fit(X_train, y_train, epochs=5, batch_size=32)

Epoch 1/5
70769/70769 ━━━━━━━━━━━━━━━━━━━━ 165s 2ms/step - accuracy: 0.9658 - loss: 0.0964
Epoch 2/5
70769/70769 ━━━━━━━━━━━━━━━━━━━━ 166s 2ms/step - accuracy: 0.9779 - loss: 0.0533
Epoch 3/5
70769/70769 ━━━━━━━━━━━━━━━━━━━━ 162s 2ms/step - accuracy: 0.9811 - loss: 0.0471
Epoch 4/5
70769/70769 ━━━━━━━━━━━━━━━━━━━━ 162s 2ms/step - accuracy: 0.9827 - loss: 0.0434
Epoch 5/5
70769/70769 ━━━━━━━━━━━━━━━━━━━━ 163s 2ms/step - accuracy: 0.9839 - loss: 0.0404

In [29]:
loss, accuracy = model.evaluate(X_test, y_test)
print('Test Loss:', loss)
print('Test Accuracy:', accuracy)

17693/17693 ━━━━━━━━━━━━━━━━━━━━ 33s 2ms/step - accuracy: 0.9843 - loss: 0.0381
Test Loss: 0.038074370473623276
Test Accuracy: 0.984336256980896