<a href="https://colab.research.google.com/github/amriteshamr/AI-Threat-Detection/blob/main/Untitled21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

df = pd.read_csv("Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv")

df.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,54865,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,55054,109,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,55055,52,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,46236,34,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,54863,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 225745 entries, 0 to 225744
Data columns (total 79 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0    Destination Port             225745 non-null  int64
 1    Flow Duration                225745 non-null  int64
 2    Total Fwd Packets            225745 non-null  int64
 3    Total Backward Packets       225745 non-null  int64
 4   Total Length of Fwd Packets   225745 non-null  int64
 5    Total Length of Bwd Packets  225745 non-null  int64
 6    Fwd Packet Length Max        225745 non-null  int64
 7    Fwd Packet Length Min        225745 non-null  int64
 8    Fwd Packet Length Mean       225745 non-null  float64
 9    Fwd Packet Length Std        225745 non-null  float64
 10  Bwd Packet Length Max         225745 non-null  int64
 11   Bwd Packet Length Min        225745 non-null  int64
 12   Bwd Packet Length Mean       225745 non-null  float64
 13   Bwd Packet Length Std        225745 non-null  float64
 14  Flow Bytes/s                  225741 non-null  float64
 15   Flow Packets/s               225745 non-null  float64
 16   Flow IAT Mean                225745 non-null  float64
 17   Flow IAT Std                 225745 non-null  float64
 18   Flow IAT Max                 225745 non-null  int64
 19   Flow IAT Min                 225745 non-null  int64
 20  Fwd IAT Total                 225745 non-null  int64
 21   Fwd IAT Mean                 225745 non-null  float64
 22   Fwd IAT Std                  225745 non-null  float64
 23   Fwd IAT Max                  225745 non-null  int64
 24   Fwd IAT Min                  225745 non-null  int64
 25  Bwd IAT Total                 225745 non-null  int64
 26   Bwd IAT Mean                 225745 non-null  float64
 27   Bwd IAT Std                  225745 non-null  float64
 28   Bwd IAT Max                  225745 non-null  int64
 29   Bwd IAT Min                  225745 non-null  int64
 30  Fwd PSH Flags                 225745 non-null  int64
 31   Bwd PSH Flags                225745 non-null  int64
 32   Fwd URG Flags                225745 non-null  int64
 33   Bwd URG Flags                225745 non-null  int64
 34   Fwd Header Length            225745 non-null  int64
 35   Bwd Header Length            225745 non-null  int64
 36  Fwd Packets/s                 225745 non-null  float64
 37   Bwd Packets/s                225745 non-null  float64
 38   Min Packet Length            225745 non-null  int64
 39   Max Packet Length            225745 non-null  int64
 40   Packet Length Mean           225745 non-null  float64
 41   Packet Length Std            225745 non-null  float64
 42   Packet Length Variance       225745 non-null  float64
 43  FIN Flag Count                225745 non-null  int64
 44   SYN Flag Count               225745 non-null  int64
 45   RST Flag Count               225745 non-null  int64
 46   PSH Flag Count               225745 non-null  int64
 47   ACK Flag Count               225745 non-null  int64
 48   URG Flag Count               225745 non-null  int64
 49   CWE Flag Count               225745 non-null  int64
 50   ECE Flag Count               225745 non-null  int64
 51   Down/Up Ratio                225745 non-null  int64
 52   Average Packet Size          225745 non-null  float64
 53   Avg Fwd Segment Size         225745 non-null  float64
 54   Avg Bwd Segment Size         225745 non-null  float64
 55   Fwd Header Length.1          225745 non-null  int64
 56  Fwd Avg Bytes/Bulk            225745 non-null  int64
 57   Fwd Avg Packets/Bulk         225745 non-null  int64
 58   Fwd Avg Bulk Rate            225745 non-null  int64
 59   Bwd Avg Bytes/Bulk           225745 non-null  int64
 60   Bwd Avg Packets/Bulk         225745 non-null  int64
 61  Bwd Avg Bulk Rate             225745 non-null  int64
 62  Subflow Fwd Packets           225745 non-null  int64
 63   Subflow Fwd Bytes            225745 non-null  int64
 64   Subflow Bwd Packets          225745 non-null  int64
 65   Subflow Bwd Bytes            225745 non-null  int64
 66  Init_Win_bytes_forward        225745 non-null  int64
 67   Init_Win_bytes_backward      225745 non-null  int64
 68   act_data_pkt_fwd             225745 non-null  int64
 69   min_seg_size_forward         225745 non-null  int64
 70  Active Mean                   225745 non-null  float64
 71   Active Std                   225745 non-null  float64
 72   Active Max                   225745 non-null  int64
 73   Active Min                   225745 non-null  int64
 74  Idle Mean                     225745 non-null  float64
 75   Idle Std                     225745 non-null  float64
 76   Idle Max                     225745 non-null  int64
 77   Idle Min                     225745 non-null  int64
 78   Label                        225745 non-null  object
dtypes: float64(24), int64(54), object(1)
memory usage: 136.1+ MB

In [4]:
df.columns = df.columns.str.strip()

In [5]:
print(df["Label"].value_counts())

Label
DDoS      128027
BENIGN     97718
Name: count, dtype: int64

In [6]:
X = df.drop("Label", axis=1)
y = df["Label"]

In [7]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
import numpy as np

inf_counts = np.isinf(X).sum()

print(inf_counts[inf_counts>0])

Flow Bytes/s      30
Flow Packets/s    34
dtype: int64

In [11]:
df = df.replace([np.inf, -np.inf], np.nan)

In [12]:
df = df.dropna()

In [13]:
X = df.drop("Label", axis=1)
y = df["Label"]

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [16]:
y_pred = model.predict(X_test)

In [17]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

      BENIGN       1.00      1.00      1.00     19419
        DDoS       1.00      1.00      1.00     25724

    accuracy                           1.00     45143
   macro avg       1.00      1.00      1.00     45143
weighted avg       1.00      1.00      1.00     45143

In [18]:
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nConfusion matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9999113926854661

Confusion matrix:
[[19419     0]
 [    4 25720]]

In [19]:
importances = model.feature_importances_

In [21]:
feature_impo = pd.DataFrame({'Feature':X.columns, 'Importance': importances}).sort_values('Importance', ascending=False)

In [22]:
feature_impo.head()

                   Feature  Importance
66  Init_Win_bytes_forward    0.080629
6    Fwd Packet Length Max    0.080526
53    Avg Fwd Segment Size    0.071837
8   Fwd Packet Length Mean    0.064787
63       Subflow Fwd Bytes    0.059407

In [23]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(model, X, y, cv=5)
print("Cross-validation scores:", scores)
print("Mean accuracy:", scores.mean())

Cross-validation scores: [0.99993354 0.99993354 0.99984493 0.99993354 0.99926897]
Mean accuracy: 0.9997829075648198